### ISSUE TITLE
URetinex-Net的复现

### ISSUE THREAD

**Issue by 1791125491** [Ysz2022/NeRCo#1]
您好，请问您对于URetinex-Net的复现是如何做的呢，我看他们没有给训练函数和损失函数的文件，如果方便的话可以提供URetinex-Net的复现代码嘛，万分感谢

**Comment by Ysz2022** [comment]
Thanks for your interest in our work :)
As mentioned in Sec. 4.2 of our paper, we obtain quantitative results of other methods by adopting their official publicated pre-trained models and running their respective public codes. Specifically, for URetinex, we download its model weights for evaluation.
Best Regards

**Comment by 1791125491** [comment]
Thanks for your reply ：
For URetinex-Net replication, I used the pre-training model provided by them for testing, but the test results on the LOL dataset are slightly different from those in your paper. Could you please provide the code of PSNR and SSIM if convenient.

**Comment by Ysz2022** [comment]
Sure, please leave your email and we will send you the code later

**Comment by 1791125491** [comment]
1791125491@qq.com
Thanks!

**Comment by Ysz2022** [comment]
We have send you code, please check your email :)

**Comment by 1318527945** [comment]
您好，目前我下载的关于URetinex-Net的代码是没有训练函数部分的，如果方便的话可以提供URetinex-Net的复现代码嘛，万分感谢
