### ISSUE TITLE
training dataset design

### ISSUE THREAD

**Issue by cxsweet** [Ysz2022/NeRCo#10]
May I ask if it is necessary to train the model using one's own dataset? Do the data in the dataset need to be paired? For example, for dim and bright images in the same scene (it is required to first capture dim images before lighting to capture bright images when creating a dataset)% 0A, or does it mean that as long as the dim and bright images in the same scene are present, there is no requirement for background consistency

**Comment by Ysz2022** [comment]
Our method is self-supervised (or unsupervised), you can train model by random bright images and dark images. There is no requirement for pairing

**Comment by cxsweet** [comment]
> Our method is self-supervised (or unsupervised), you can train model by random bright images and dark images. There is no requirement for pairing

Thank you for your answer. I have just started learning this knowledge and there are still many areas I don't understand

**Comment by Ysz2022** [comment]
Thanks for your interest :)

BTW, I will temporally close this issue, you are welcome to reopen it if you have any further questions!
