### ISSUE TITLE
Access to the pre-trained model

### ISSUE THREAD

**Issue by farkoo** [Ysz2022/NeRCo#12]
Dear All,

I wanted to extend my gratitude for generously sharing your code.
I kindly ask if it's feasible to grant me access to your pre-trained model. It would significantly contribute to my ongoing research.

Thank you sincerely for your consideration.
Best Regards.

**Comment by Ysz2022** [comment]
Of course, you're free to download our released model weights.

**Comment by farkoo** [comment]
> Of course, you're free to download our released model weights.

Thanks a lot. I found the links to the models in the readme file.
