### ISSUE TITLE
图片分辨率

### ISSUE THREAD

**Issue by cxsweet** [Ysz2022/NeRCo#13]
testB中的图片的尺寸一定要跟testA中图片的尺寸一致吗？可以自适应调整吗？如果可以的话应该在哪里修改啊？麻烦解答

**Comment by Ysz2022** [comment]
没必要一致，随便放一张就行

**Comment by cxsweet** [comment]
> 没必要一致，随便放一张就行

但我test的过程中如果不一致就会报错
![20231223171945](https://github.com/Ysz2022/NeRCo/assets/91363416/742d9d88-a821-4849-b720-36b55913d4a2)
报错信息：RuntimeError: The size of tensor a (376) must match the size of tensor b (640) at non-singleton dimension 3

**Comment by Ysz2022** [comment]
不好意思，我们给的默认代码在测试时确实需要testA和testB中的图片大小一致。但也可以作调整

在models/NeRCo_model.py的第100-112行是我们模型的前向函数，你可以注释掉需要输入testB中数据的部分，即，第109-112行即可。因为fake_B就是我们增强后的结果。

如果你有进一步的问题，欢迎提问:)

**Comment by cxsweet** [comment]
> 不好意思，我们给的默认代码在测试时确实需要testA和testB中的图片大小一致。但也可以作调整
> 
> 在models/NeRCo_model.py的第100-112行是我们模型的前向函数，你可以注释掉需要输入testB中数据的部分，即，第109-112行即可。因为fake_B就是我们增强后的结果。
> 
> 如果你有进一步的问题，欢迎提问:)

哇谢谢！！！我自己看了好久

**Comment by Ysz2022** [comment]
感谢您对我们工作的兴趣 :)
