### ISSUE TITLE
multi gpus

### ISSUE THREAD

**Issue by MikeQ0425** [Ysz2022/NeRCo#4]
How can i run your code on multi gpus? I change the parameter 'gpu_ids' but it didnt work.

**Comment by Ysz2022** [comment]
Thanks for your interest in our work :). I am very sorry that our code cannot run on multiple GPUs yet (at least I haven't tried it before).

You can change the input resolution by adjusting "load_size", "crop_size", and "display_winsize" in base_options.py in the options directory. Noting that "preprocess" should be set as "resize_and_crop".

Further, if I have time, I will try to make my code be able to run on multiple GPUs! 😊

**Comment by MikeQ0425** [comment]
Thank you for your reply and your amazing job.I will try your suggestions,hope it can be work.



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ysz2022/NeRCo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月27日(星期四) 下午5:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ysz2022/NeRCo] multi gpus (Issue #4)





 
Thanks for your interest in our work :). I am very sorry that our code cannot run on multiple GPUs yet (at least I haven't tried it before).
 
You can change the input resolution by adjusting "load_size", "crop_size", and "display_winsize" in base_options.py in the options directory. Noting that "preprocess" should be set as "resize_and_crop".
 
Further, if I have time, I will try to make my code be able to run on multiple GPUs! 😊

**Comment by Ysz2022** [comment]
Thanks for your interest again :).

BTW, I will temporally close this issue, you are welcome to reopen it if you have any further questions!
