### ISSUE TITLE
Eval matric

### ISSUE THREAD

**Issue by zhangbaijin** [Ysz2022/NeRCo#6]
Good work! can you share me your code about NIQE and LOE？my email is framebreak@sjtu.edu.cn

**Comment by Ysz2022** [comment]
We calculate NIQE by using code from here: https://github.com/guptapraful/niqe

We have sent the code of LOE to your email.

**Comment by CharlesYTJ** [comment]
Could you also send me a code for calculating LOE?
Email: Charlesjyt@163.com

Thanks.

**Comment by Ysz2022** [comment]
Sure! We have sent the code of LOE to your email.

**Comment by xiaolong-217** [comment]
Can you also send me a code to calculate the LOE? 
My e-mail : liujiaw0217@163.com
thanks!

**Comment by Ysz2022** [comment]
你好，已发

**Comment by Ysz2022** [comment]
I have sent it, please check your email :)
