### ISSUE TITLE
NIQE metric

### ISSUE THREAD

**Issue by CharlesYTJ** [Ysz2022/NeRCo#7]
Can you send me the code to calculate the NIQE metric to my email?

Email: Charlesjyt@163.com

**Comment by CharlesYTJ** [comment]
Thank you for your help. I found the NIQE code in another comment section.

**Comment by Ysz2022** [comment]
We calculate NIQE by using code from here: https://github.com/guptapraful/niqe

**Comment by CharlesYTJ** [comment]
Thanks.
